PRAGMA foreign_keys=OFF;

ALTER TABLE content_items RENAME TO content_items_before_articles;

CREATE TABLE content_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  kind TEXT NOT NULL CHECK (kind IN ('projects','experiences','education','certifications','skills','socials','documents','articles')),
  slug TEXT NOT NULL,
  data TEXT NOT NULL DEFAULT '{}',
  sort_order INTEGER NOT NULL DEFAULT 0,
  visible INTEGER NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(kind, slug)
);

INSERT INTO content_items(id,kind,slug,data,sort_order,visible,created_at,updated_at)
SELECT id,kind,slug,data,sort_order,visible,created_at,updated_at FROM content_items_before_articles;
DROP TABLE content_items_before_articles;
CREATE INDEX idx_content_kind_order ON content_items(kind, sort_order, id);

-- Projects are replaced as a deliberate editorial set. Items in which Gökçe
-- had no role are omitted rather than presented as company-wide work.
DELETE FROM content_items WHERE kind='projects';

INSERT INTO content_items(kind,slug,data,sort_order,visible) VALUES
('projects','galerion','{"featured":true,"name_tr":"Galerion","name_en":"Galerion","description_tr":"Otomotiv galerilerinin stok, müşteri ve operasyon süreçlerini tek yerde yönettiği çok kiracılı platform.","description_en":"A multi-tenant platform for automotive dealerships to manage inventory, customers and operations in one place.","role_tr":"Full-Stack Yazılım Mühendisi","role_en":"Full-Stack Software Engineer","problem_tr":"Galeri operasyonları araç stokları, müşteri ilişkileri, belgeler, giderler ve galeriler arası paylaşım gibi birbirine bağlı süreçlerden oluşuyordu. Şirket bu süreçleri ortak bir üründe birleştirmek istedi.","problem_en":"Dealership operations span connected workflows such as vehicle inventory, customer relations, documents, expenses and inventory sharing. The company set out to bring these processes into one product.","body_tr":"Çok kiracılı ve rol tabanlı mimariye; araç, CRM, doküman, gider ve raporlama modüllerine katkı verdim. Galeriler arası araç paylaşımı, fiyatlandırma/değerleme ve konum tabanlı özellikler üzerinde backend, web ve mobil API geliştirmeleri yaptım.","body_en":"I contributed to the multi-tenant, role-based architecture and to vehicle, CRM, document, expense and reporting modules. I delivered backend, web and mobile API work for cross-dealer inventory sharing, pricing and valuation, and geospatial features.","highlights_tr":"Multi-tenant ve rol tabanlı yetkilendirme\nAraç, CRM, doküman, gider ve raporlama akışları\nGaleriler arası stok paylaşımı ve konum tabanlı özellikler","highlights_en":"Multi-tenant, role-based authorization\nVehicle, CRM, document, expense and reporting workflows\nCross-dealer inventory sharing and geospatial capabilities","outcome_tr":"Ürün 2026 itibarıyla 108 kayıtlı galeriye ulaştı.","outcome_en":"By 2026, the product had reached 108 registered dealerships.","technical_notes_tr":"PostgreSQL/PostGIS, Redis ve Celery; ilişkisel veriler, coğrafi sorgular ve arka plan işleri için birbirini tamamladı. Bu çalışma tenant izolasyonu ile ortak ürün geliştirme arasındaki dengeyi güçlendirdi.","technical_notes_en":"PostgreSQL/PostGIS, Redis and Celery complemented one another across relational data, geospatial queries and background jobs. The work strengthened my understanding of balancing tenant isolation with a shared product.","tech_stack":["Django","DRF","PostgreSQL","PostGIS","Redis","Celery","React","Docker"],"category":"company-product","status":"live","employer":"Everion Consulting","start_date":"2025-07","end_date":"2026-04","live_url":"https://galerion.com.tr","live_url_label_tr":"Ürünü incele","live_url_label_en":"View product"}',1,1),
('projects','payment-platform','{"featured":true,"name_tr":"Payment Platform","name_en":"Payment Platform","description_tr":".NET gelişimimi gerçek ödeme problemleri üzerinden derinleştirdiğim, devam eden referans proje.","description_en":"An ongoing reference project where I deepen my .NET skills through real payment-domain problems.","role_tr":"Bağımsız geliştirici","role_en":"Independent Developer","problem_tr":".NET öğrenirken yalnızca CRUD ekranları üretmek yerine transaction, idempotency, webhook ve mutabakat gibi hata toleransı gerektiren bir alan üzerinde çalışmak istedim.","problem_en":"While learning .NET, I wanted to work on a failure-sensitive domain involving transactions, idempotency, webhooks and reconciliation rather than build another CRUD application.","body_tr":"ASP.NET Core ile ödeme orkestrasyonu, idempotent istek işleme, webhook doğrulama, ledger kayıtları ve mutabakat akışlarını modelleyen bir platform geliştiriyorum.","body_en":"I am building an ASP.NET Core platform that models payment orchestration, idempotent request handling, webhook verification, ledger entries and reconciliation workflows.","highlights_tr":"Idempotent ödeme istekleri\nWebhook işleme ve yeniden deneme\nLedger ve mutabakat modeli","highlights_en":"Idempotent payment requests\nWebhook processing and retries\nLedger and reconciliation model","outcome_tr":"Canlı bir finansal ürün değil; .NET ve ödeme sistemleri konusunda üretim odaklı düşünme pratiği sağlayan devam eden bir referans çalışma.","outcome_en":"This is not a live financial product; it is an ongoing reference project for production-minded practice in .NET and payment systems.","technical_notes_tr":"ASP.NET Core seçimi .NET ekosistemini derinleştirmemi sağlıyor. Basit durum güncellemeleri yerine immutable ledger kayıtları ve idempotency anahtarları kullanmak finansal tutarlılık açısından daha güvenli bir yaklaşım.","technical_notes_en":"ASP.NET Core lets me deepen my knowledge of the .NET ecosystem. Immutable ledger records and idempotency keys provide safer financial consistency than simple state updates.","tech_stack":["C#","ASP.NET Core","PostgreSQL","Docker"],"category":"personal","status":"in-progress","start_date":"2026-08","end_date":"Present"}',2,1),
('projects','maritimeos','{"featured":true,"name_tr":"MaritimeOS","name_en":"MaritimeOS","description_tr":"Değişken denizcilik operasyonlarını yapılandırılabilir iş akışlarıyla dijitalleştirmeyi amaçlayan platform.","description_en":"A platform designed to digitize variable maritime operations through configurable workflows.","role_tr":"Ürün fikri ve bağımsız geliştirme","role_en":"Product Concept and Independent Development","problem_tr":"Bir denizcilik şirketinde operasyonların hâlâ Excel ve WhatsApp üzerinden ilerlediğini gördüm. Ancak her şirketin iş akışı farklı olduğu için sabit süreçlere dayanan tek bir uygulama yeterli olmayacaktı.","problem_en":"I saw maritime operations still being managed through Excel and WhatsApp. Because each company follows different workflows, a single application built around fixed processes would not be enough.","body_tr":"Salesforce platform yaklaşımından da esinlenerek alan kuralları, durum makineleri ve birbirine bağımlı görevlerle yapılandırılabilir bir operasyon sistemi geliştiriyorum.","body_en":"Inspired in part by Salesforce as a platform, I am building a configurable operations system with domain rules, state machines and dependency-aware tasks.","highlights_tr":"Yapılandırılabilir iş akışları\nDurum makineleri ve alan sınırları\nBağımlılıkları izleyen görev yönetimi","highlights_en":"Configurable workflows\nState machines and domain boundaries\nDependency-aware task management","outcome_tr":"Proje hâlen geliştirme aşamasında; üretim veya kullanıcı sayısı iddiası taşımıyor.","outcome_en":"The project is still in development and makes no production or user-count claims.","technical_notes_tr":"Go, açık servis sınırları ve eşzamanlı işler için bilinçli bir tercih oldu. PostgreSQL entegrasyon testleri, iş kurallarını yalnızca mocklar üzerinden değil gerçek veritabanı davranışıyla doğrulamamı sağlıyor.","technical_notes_en":"Go was a deliberate choice for clear service boundaries and concurrent work. PostgreSQL integration tests validate business rules against real database behavior rather than mocks alone.","tech_stack":["Go","PostgreSQL","Next.js","Docker"],"category":"personal","status":"in-progress","start_date":"2026-06","end_date":"Present"}',3,1),
('projects','portfolio-site','{"featured":true,"name_tr":"gokceguler.com","name_en":"gokceguler.com","description_tr":"Portfolyo sunumunu içerik yönetimi, analitik ve CV aktarımıyla gerçek bir ürüne dönüştüren kişisel platform.","description_en":"A personal platform that turns portfolio presentation into a real product with content management, analytics and CV import.","role_tr":"Bağımsız geliştirici","role_en":"Independent Developer","problem_tr":"Klasik statik bir portfolyo yerine düzenli kullanacağım bir ürün geliştirerek Go deneyimimi gerçek bir sistem üzerinde artırmak istedim.","problem_en":"Instead of another static portfolio, I wanted to deepen my Go experience through a real system that I would continue to use.","body_tr":"Go REST API, Next.js arayüz ve kendi yönetim panelimi geliştirdim. İki dilli içerik, gizlilik odaklı analitik, inceleme adımlı PDF CV içe aktarma, içerik sağlığı, belge yönetimi ve teknik SEO özelliklerini bir araya getirdim.","body_en":"I built a Go REST API, a Next.js interface and a custom admin panel. It combines bilingual content, privacy-conscious analytics, review-first PDF résumé import, content health, document management and technical SEO.","highlights_tr":"Özel içerik yönetim paneli\nİki dilli içerik ve teknik SEO\nGizlilik odaklı analitik\nİnceleme adımlı PDF CV aktarımı","highlights_en":"Custom content management panel\nBilingual content and technical SEO\nPrivacy-conscious analytics\nReview-first PDF résumé import","outcome_tr":"Sürekli geliştirdiğim ve kendi içerik süreçlerimde kullandığım canlı portfolyo altyapısı.","outcome_en":"A live portfolio platform that I continuously improve and use for my own content workflow.","technical_notes_tr":"Go ile küçük ve açık bir API katmanı kurmayı; Next.js ile erişilebilir, SEO uyumlu ve iki dilli bir arayüz üretmeyi seçtim. İçeriği koddan ayırmak güncellemeleri daha güvenli hâle getirdi.","technical_notes_en":"I chose Go for a small, explicit API layer and Next.js for an accessible, SEO-friendly bilingual interface. Separating content from code made ongoing updates safer.","tech_stack":["Go","chi","SQLite","Next.js","TypeScript","Docker"],"category":"personal","status":"live","start_date":"2026-09","end_date":"Present"}',4,1),
('projects','hasarlink','{"featured":false,"name_tr":"HasarLink","name_en":"HasarLink","description_tr":"Oto hasar onarım uzmanları ve servisler için dosya ve operasyon yönetimi platformu.","description_en":"A case and operations management platform for auto damage repair specialists and service centers.","role_tr":"Backend ve ürün geliştirme katkısı","role_en":"Backend and Product Engineering Contributor","problem_tr":"Hasar dosyalarının belge, bildirim ve farklı kullanıcı rolleri arasında düzenli ilerlemesi; sahadaki veri girişinin de hızlandırılması gerekiyordu.","problem_en":"Damage cases needed to move reliably across documents, notifications and multiple user roles, while field data entry also needed to become faster.","body_tr":"Projeye başlangıç mimarisi ve veri modeliyle katkı verdim. Firebase push bildirim altyapısını ve Doc AI entegrasyonunu kurdum; Docker tabanlı yayın mimarisini tasarladım ve Google Play yayın/sürüm süreçlerini takip ettim.","body_en":"I contributed to the initial architecture and data model. I set up Firebase push notifications and the Doc AI integration, designed the Docker-based deployment architecture, and followed Google Play release and versioning work.","highlights_tr":"Başlangıç mimarisi ve veri modeli\nFirebase push bildirimleri\nDoc AI ile hızlı form doldurma\nGoogle Play yayın takibi","highlights_en":"Initial architecture and data model\nFirebase push notifications\nFaster form entry through Doc AI\nGoogle Play release follow-up","outcome_tr":"Üretimde kullanılan ve Google Play’de 100+ indirmeye ulaşan ürünün önemli teknik parçalarına katkı verdim.","outcome_en":"I contributed important technical parts of a production product that reached 100+ downloads on Google Play.","technical_notes_tr":"Belge tanıma ve bildirimleri ana iş akışından ayırmak, kullanıcı deneyimini hızlandırırken servis sınırlarını daha yönetilebilir tuttu.","technical_notes_en":"Separating document recognition and notifications from the main workflow improved user experience while keeping service boundaries manageable.","tech_stack":["Django","DRF","PostgreSQL","Firebase","Docker","Google Gemini API"],"category":"company-product","status":"live","employer":"Everion Consulting","start_date":"2025-06","end_date":"2026-02","live_url":"https://play.google.com/store/apps/details?id=com.everionconsulting.dbappnews&hl=en_GB","live_url_label_tr":"Google Play’de incele","live_url_label_en":"View on Google Play"}',5,1),
('projects','doc-ai','{"featured":false,"name_tr":"Doc AI","name_en":"Doc AI","description_tr":"Belgelerden yapılandırılmış veri çıkararak ürünlerde form doldurmayı hızlandıran yapay zekâ servisi.","description_en":"An AI service that accelerates form completion by extracting structured data from documents.","role_tr":"Backend ve AI geliştiricisi","role_en":"Backend and AI Engineer","problem_tr":"Kullanıcılar farklı belge türlerindeki bilgileri formlara elle aktarıyor, bu da zaman kaybına ve veri giriş hatalarına neden oluyordu.","problem_en":"Users manually transferred information from many document types into forms, creating delays and data-entry errors.","body_tr":"Google Gemini API ile belge alımı, sınıflandırma, çoklu dosya analizi, yapılandırılmış JSON üretimi ve hata yönetimini geliştirdim. Servisi üretimde kullanılan ürünlerin form akışlarına entegre ettim.","body_en":"Using the Google Gemini API, I developed document ingestion, classification, multi-file analysis, structured JSON output and error handling. I integrated the service into form workflows used by production products.","highlights_tr":"22 belge kategorisi\nÇoklu dosya analizi\nYapılandırılmış ve doğrulanabilir çıktı\nÜrünler arası yeniden kullanılabilir servis","highlights_en":"22 document categories\nMulti-file analysis\nStructured, verifiable output\nReusable service across products","outcome_tr":"Ortalama işlem süresi yaklaşık 6 saniyeye inerken, örnek form akışı 7–8 dakikadan yaklaşık 50 saniyeye düştü.","outcome_en":"Average processing time fell to about six seconds, while a representative form workflow dropped from 7–8 minutes to roughly 50 seconds.","technical_notes_tr":"LLM çıktısını doğrudan kullanmak yerine şemalı JSON, doğrulama ve hata akışları eklemek entegrasyonları daha öngörülebilir hâle getirdi.","technical_notes_en":"Using schema-constrained JSON, validation and explicit error paths instead of consuming raw LLM output made integrations more predictable.","tech_stack":["Django","DRF","Celery","Redis","Google Gemini API","PostgreSQL"],"category":"company-product","status":"live","employer":"Everion Consulting","start_date":"2025-11","end_date":"2026-01"}',6,1),
('projects','qrakter','{"featured":false,"name_tr":"QRakter","name_en":"QRakter","description_tr":"Kaza anı desteği ve dijital tutanak süreçlerini kolaylaştıran mobil platform.","description_en":"A mobile platform that simplifies accident assistance and digital reporting workflows.","role_tr":"Doc AI entegrasyonu ve yayın katkısı","role_en":"Doc AI Integration and Release Contributor","problem_tr":"Ruhsat, ehliyet ve kasko poliçesindeki bilgilerin mobil formlara elle girilmesi kaza anındaki süreci yavaşlatıyordu.","problem_en":"Manually entering vehicle registration, driver’s license and insurance policy data into mobile forms slowed down an already stressful accident workflow.","body_tr":"Ekip içinde Doc AI entegrasyonunu geliştirerek yüklenen belgelerden form alanlarının hızlı doldurulmasını sağladım. Ürünün yayın sürecine de katkı verdim.","body_en":"As part of the team, I built the Doc AI integration that quickly populates form fields from uploaded documents. I also contributed to the release process.","highlights_tr":"Ruhsat, ehliyet ve kasko belgesi işleme\nMobil form alanlarının otomatik doldurulması\nYayın sürecine ekip katkısı","highlights_en":"Vehicle registration, driver’s license and insurance document processing\nAutomatic mobile form completion\nTeam contribution to the release","outcome_tr":"Google Play’de 1.000+ indirmeye ulaşan ürünün belge işleme deneyimini hızlandırdım.","outcome_en":"I accelerated document entry in a product that reached 1,000+ downloads on Google Play.","technical_notes_tr":"Mobil akışta AI entegrasyonunu küçük ve geri alınabilir adımlarla kurmak, hatalı alanların kullanıcı tarafından kontrol edilmesini mümkün kıldı.","technical_notes_en":"Integrating AI through small, reversible steps in the mobile flow allowed users to review and correct uncertain fields.","tech_stack":["Django","DRF","React Native","Expo","Google Gemini API"],"category":"company-product","status":"live","employer":"Everion Consulting","start_date":"2025-12","end_date":"2026-03","live_url":"https://play.google.com/store/apps/details?id=com.everion.qrakter.app&hl=tr","live_url_label_tr":"Google Play’de incele","live_url_label_en":"View on Google Play"}',7,1),
('projects','everion-marketing','{"featured":false,"name_tr":"Everion Marketing","name_en":"Everion Marketing","description_tr":"Saha ekipleri için konum tabanlı müşteri, ziyaret ve raporlama platformu.","description_en":"A location-based customer, visit and reporting platform for field teams.","role_tr":"Full-Stack geliştirme ve entegrasyon katkısı","role_en":"Full-Stack Engineering and Integration Contributor","problem_tr":"Saha ekiplerinin müşteri ziyaretlerini, konum uyumunu ve raporlamayı tek bir mobil akışta takip etmesi gerekiyordu.","problem_en":"Field teams needed one mobile workflow for customer visits, location compliance and reporting.","body_tr":"Projeye sonradan katılarak çeşitli frontend ve backend geliştirmeleri yaptım. Google Places API, harita/konum, uzak konum ihlali ve raporlama özellikleriyle birlikte Doc AI entegrasyonuna katkı verdim; Google Play yayınını takip ettim.","body_en":"I joined the project later and delivered several frontend and backend improvements. I contributed Google Places API, map and location features, remote-location violation controls, reporting and Doc AI integration, and followed the Google Play release.","highlights_tr":"Google Places API entegrasyonu\nHarita ve konum kontrolleri\nUzak konum ihlali ve raporlama\nDoc AI entegrasyonu","highlights_en":"Google Places API integration\nMap and location controls\nRemote-location violations and reporting\nDoc AI integration","outcome_tr":"Mevcut ürüne sonradan dahil olup konum, belge işleme ve yayın taraflarında somut özellikler teslim ettim.","outcome_en":"After joining an existing product, I shipped concrete location, document-processing and release improvements.","technical_notes_tr":"Google Places verisini uygulama içi konum kurallarıyla ayırmak, harici servis değişikliklerine karşı daha sürdürülebilir bir entegrasyon sağladı.","technical_notes_en":"Separating Google Places data from application-specific location rules produced a more maintainable external integration.","tech_stack":["Django","DRF","React Native","PostgreSQL","Google Places API","Google Gemini API"],"category":"company-product","status":"live","employer":"Everion Consulting","start_date":"2026-01","end_date":"2026-03","live_url":"https://www.everionconsulting.com/tr/projeler","live_url_label_tr":"Proje sayfasını incele","live_url_label_en":"View project page"}',8,1),
('projects','koza','{"featured":false,"name_tr":"Koza","name_en":"Koza","description_tr":"Şirket içi proje, görev, doküman, toplantı ve mesai yönetimi web uygulaması.","description_en":"An internal web application for project, task, document, meeting and attendance management.","role_tr":"Backend ve entegrasyon geliştiricisi","role_en":"Backend and Integration Engineer","problem_tr":"Şirket içindeki proje takibi farklı araçlara dağılıyordu. Ayrıca çalışanların mesai takibini manuel yürütmek zaman alıyordu.","problem_en":"Internal project tracking was spread across different tools, while manually tracking employee hours was time-consuming.","body_tr":"Çeşitli backend geliştirmelerine katkı verdim. Doküman editöründe metin ve tablo üretebilen Gemini AI asistanını, toplantı takibi için Google Calendar entegrasyonunu ve QR ile mesai takibi modülünü geliştirdim.","body_en":"I contributed several backend improvements. I built a Gemini AI assistant that creates text and tables inside the document editor, a Google Calendar integration for meeting tracking, and a QR-based attendance module.","highlights_tr":"Gemini destekli doküman ve tablo üretimi\nGoogle Calendar toplantı entegrasyonu\nQR tabanlı mesai takibi","highlights_en":"Gemini-assisted document and table generation\nGoogle Calendar meeting integration\nQR-based attendance tracking","outcome_tr":"Bana verilen manuel mesai takibi sorumluluğunu, şirket içinde yeniden kullanılabilen bir yazılım modülüne dönüştürdüm.","outcome_en":"I turned a manual attendance-tracking responsibility into a reusable internal software module.","technical_notes_tr":"Mesai modülünde QR kullanımını basit bir giriş noktası olarak seçtim; kayıtların yetki ve zaman kontrollerini backend’de tutmak istemci manipülasyonu riskini azalttı.","technical_notes_en":"I chose QR as a simple entry point for attendance, while keeping authorization and time validation on the backend to reduce client-side manipulation risks.","tech_stack":["Django","DRF","React","PostgreSQL","Google Gemini API","Google Calendar API"],"category":"internal-product","status":"internal","employer":"Everion Consulting","start_date":"2026-04","end_date":"2026-07"}',9,1),
('projects','notification-kit','{"featured":false,"name_tr":"Notification Kit","name_en":"Notification Kit","description_tr":"Django projeleri için e-posta, SMS ve push gönderimini ortaklaştıran genişletilebilir bildirim paketi.","description_en":"An extensible Django package that unifies email, SMS and push delivery.","role_tr":"Paket geliştiricisi","role_en":"Package Developer","problem_tr":"Ekipte yeni projelere bildirim sistemi eklenirken aynı altyapı tekrar kuruluyor ve benzer entegrasyon sorunları yaşanıyordu.","problem_en":"The team repeatedly rebuilt notification infrastructure for new projects and encountered the same integration problems.","body_tr":"API, servis, backend ve task katmanlarını ayıran yeniden kullanılabilir bir Django paketi geliştirdim ve PyPI’da yayımladım. Şablonlar, kullanıcı tercihleri, toplu/asenkron gönderim, retry, throttling, loglama ve özel backend desteği ekledim.","body_en":"I developed and published a reusable Django package on PyPI with separate API, service, backend and task layers. It supports templates, user preferences, batch and asynchronous delivery, retries, throttling, logging and custom backends.","highlights_tr":"E-posta, SMS ve push kanalları\nCelery ile asenkron ve zamanlanmış gönderim\nDRF API, tercihler, loglama ve rate limiting\nGenişletilebilir özel backend yapısı","highlights_en":"Email, SMS and push channels\nAsynchronous and scheduled delivery with Celery\nDRF API, preferences, logging and rate limiting\nExtensible custom backend architecture","outcome_tr":"1.2.0 sürümü 13 Şubat 2026’da PyPI’da yayımlandı. Özel GitHub deposu portföyde paylaşılmıyor.","outcome_en":"Version 1.2.0 was published on PyPI on February 13, 2026. Its private GitHub repository is not shared in the portfolio.","technical_notes_tr":"Katmanlı yapı sağlayıcı bağımlılıklarını iş kurallarından ayırdı. Alternatif olarak her projede ayrı entegrasyon yazılabilirdi; paket yaklaşımı tekrar eden kodu ve kurulum kararlarını ortaklaştırdı.","technical_notes_en":"The layered structure separates provider dependencies from business rules. Building integrations separately in every project was possible, but a package centralized repeated code and setup decisions.","tech_stack":["Python","Django","DRF","Celery","Redis","PyPI"],"category":"package","status":"published","employer":"Everion Consulting","start_date":"2026-02","end_date":"2026-02","live_url":"https://pypi.org/project/notification-kit/1.2.0/","live_url_label_tr":"PyPI’da incele","live_url_label_en":"View on PyPI","presentation_url":"/documents/Notification-Kit-Paketini-Projenize-Entegre-Etme.pdf"}',10,1);

-- Restore the Everion experience removed by migration 005, with contribution
-- language that does not imply people management.
DELETE FROM content_items WHERE kind='experiences' AND slug IN ('software-engineer','everion-lead','everion-engineer');
INSERT INTO content_items(kind,slug,data,sort_order,visible) VALUES
('experiences','everion-lead','{"role_tr":"Yazılım Mühendisi","role_en":"Software Engineer","company":"Everion Consulting","description_tr":"Otomotiv, sigorta, CRM ve yapay zekâ destekli doküman işleme ürünlerinde backend, web ve mobil geliştirmeler yaptım. REST API’leri, asenkron servisler, üçüncü taraf entegrasyonları ve mobil yayın süreçlerinde sorumluluk aldım; şirket içi operasyon ihtiyaçlarını yazılım modüllerine dönüştürdüm.","description_en":"I delivered backend, web and mobile capabilities across automotive, insurance, CRM and AI-assisted document-processing products. I worked on REST APIs, asynchronous services, third-party integrations and mobile releases, and turned internal operational needs into software modules.","tech_stack":["Python","Django","DRF","PostgreSQL","Redis","Celery","React","React Native"],"start_date":"Mar 2025","end_date":"Present"}',1,1);

DELETE FROM content_items WHERE kind='certifications';
INSERT INTO content_items(kind,slug,data,sort_order,visible) VALUES
('certifications','salesforce-agentforce','{"name_tr":"Salesforce Certified Agentforce Specialist","name_en":"Salesforce Certified Agentforce Specialist","issuer":"Trailhead by Salesforce","year":"Aralık 2025","description_tr":"Agentforce çözümlerini iş süreçleri, güvenilir veri ve yönetişimle birlikte tasarlamaya odaklanan sertifika. Salesforce, problemlere yalnızca kod üzerinden değil; süreç, veri modeli, yetkilendirme ve otomasyon bütünlüğüyle bakmamı güçlendirdi.","description_en":"A certification focused on designing Agentforce solutions around business processes, trusted data and governance. Salesforce strengthened my ability to consider process, data modeling, permissions and automation alongside code.","credential_id":"7299567","attachment_url":"/certifications/salesforce-agentforce-specialist.png","badge_url":"/certifications/salesforce-agentforce-specialist.png"}',1,1),
('certifications','salesforce-admin','{"name_tr":"Salesforce Certified Administrator","name_en":"Salesforce Certified Administrator","issuer":"Trailhead by Salesforce","year":"Kasım 2025","description_tr":"Salesforce yapılandırması, veri modeli, güvenlik, kullanıcı yönetimi ve otomasyon yetkinliklerini doğrulayan sertifika. Platform Developer I hazırlığım, deklaratif ve programatik çözümler arasındaki seçimleri geliştirici bakışıyla derinleştiriyor.","description_en":"A certification validating Salesforce configuration, data modeling, security, user management and automation skills. My ongoing Platform Developer I preparation deepens how I evaluate declarative and programmatic solutions as a developer.","credential_id":"6959031","attachment_url":"/certifications/salesforce-platform-administrator.png","badge_url":"/certifications/salesforce-platform-administrator.png"}',2,1);

DELETE FROM content_items WHERE kind='articles';
INSERT INTO content_items(kind,slug,data,sort_order,visible) VALUES
('articles','salesforce-governor-limits','{"featured":true,"title_tr":"Salesforce Governor Limits","title_en":"Salesforce Governor Limits","summary_tr":"Salesforce kaynak sınırlarının neden var olduğunu ve ölçeklenebilir Apex geliştirirken nasıl düşünülmesi gerektiğini anlatıyorum.","summary_en":"An explanation of why Salesforce resource limits exist and how to reason about them when building scalable Apex solutions.","publication":"Everion Consulting","language":"tr","topics":["Salesforce","Apex","Architecture"],"url":"https://www.everionconsulting.com/tr/blog/60"}',1,1),
('articles','salesforce-integration-scenarios','{"featured":true,"title_tr":"Salesforce Entegrasyon Senaryoları","title_en":"Salesforce Integration Scenarios","summary_tr":"Senkron, asenkron ve olay tabanlı entegrasyon yaklaşımlarını gerçek kullanım senaryoları üzerinden karşılaştırıyorum.","summary_en":"A comparison of synchronous, asynchronous and event-driven integration approaches through practical use cases.","publication":"Everion Consulting","language":"tr","topics":["Salesforce","Integration"],"url":"https://www.everionconsulting.com/tr/blog/56"}',2,1),
('articles','django-async-programming','{"featured":true,"title_tr":"Django’da Asenkron Programlama","title_en":"Asynchronous Programming in Django","summary_tr":"Django’nun asenkron yeteneklerini, uygun kullanım alanlarını ve senkron kodla birlikte çalışırken dikkat edilmesi gerekenleri inceliyorum.","summary_en":"A practical look at Django’s asynchronous capabilities, suitable use cases and the boundaries between async and synchronous code.","publication":"Everion Consulting","language":"tr","topics":["Django","Async","Backend"],"url":"https://www.everionconsulting.com/tr/blog/55"}',3,1),
('articles','salesforce-dx-cicd','{"title_tr":"Salesforce DX ve CI/CD","title_en":"Salesforce DX and CI/CD","summary_tr":"Salesforce geliştirme yaşam döngüsünde kaynak kontrolü, otomasyon ve güvenli dağıtım yaklaşımını ele alıyorum.","summary_en":"Source control, automation and reliable deployment practices across the Salesforce development lifecycle.","publication":"Everion Consulting","language":"tr","topics":["Salesforce","CI/CD"],"url":"https://www.everionconsulting.com/tr/blog/47"}',4,1),
('articles','advanced-django-signals','{"title_tr":"İleri Seviye Django Signals","title_en":"Advanced Django Signals","summary_tr":"Signal kullanımında transaction sınırları, yan etkiler ve sürdürülebilir tasarım kararlarını inceliyorum.","summary_en":"Transaction boundaries, side effects and maintainable design decisions when working with Django signals.","publication":"Everion Consulting","language":"tr","topics":["Django","Backend"],"url":"https://www.everionconsulting.com/tr/blog/46"}',5,1),
('articles','django-signals-basics','{"title_tr":"Django Signals Temelleri","title_en":"Django Signals Basics","summary_tr":"Django signal mekanizmasının çalışma biçimini ve hangi durumlarda faydalı olduğunu örneklerle anlatıyorum.","summary_en":"An example-driven introduction to how Django signals work and when they are useful.","publication":"Everion Consulting","language":"tr","topics":["Django","Backend"],"url":"https://www.everionconsulting.com/tr/blog/39"}',6,1),
('articles','salesforce-integration-methods','{"title_tr":"10 Salesforce Entegrasyon Yöntemi","title_en":"10 Salesforce Integration Methods","summary_tr":"Salesforce’u harici sistemlere bağlamak için kullanılabilecek başlıca yöntemleri ve seçim kriterlerini özetliyorum.","summary_en":"An overview of key methods for connecting Salesforce with external systems and the criteria for choosing between them.","publication":"Everion Consulting","language":"tr","topics":["Salesforce","Integration"],"url":"https://www.everionconsulting.com/tr/blog/34"}',7,1),
('articles','drf-modern-api','{"title_tr":"Django REST Framework ile Modern API Geliştirme","title_en":"Building Modern APIs with Django REST Framework","summary_tr":"DRF ile doğrulama, yetkilendirme ve sürdürülebilir endpoint tasarımının temel parçalarını ele alıyorum.","summary_en":"The fundamentals of validation, authorization and maintainable endpoint design with Django REST Framework.","publication":"Everion Consulting","language":"tr","topics":["Django","DRF","API"],"url":"https://www.everionconsulting.com/tr/blog/32"}',8,1),
('articles','salesforce-small-business','{"title_tr":"Küçük İşletmeler İçin Salesforce","title_en":"Salesforce for Small Businesses","summary_tr":"Salesforce’un küçük işletmelerde hangi ihtiyaçlara cevap verebileceğini ve doğru kapsamın nasıl seçileceğini anlatıyorum.","summary_en":"How Salesforce can support small-business needs and how to choose an appropriate implementation scope.","publication":"Everion Consulting","language":"tr","topics":["Salesforce","CRM"],"url":"https://www.everionconsulting.com/tr/blog/31"}',9,1),
('articles','salesforce-reports-dashboards','{"title_tr":"Salesforce Raporları ve Dashboard’ları","title_en":"Salesforce Reports and Dashboards","summary_tr":"Operasyonel veriyi karar desteğine dönüştüren rapor ve dashboard yapılarını inceliyorum.","summary_en":"How reports and dashboards turn operational Salesforce data into decision support.","publication":"Everion Consulting","language":"tr","topics":["Salesforce","Analytics"],"url":"https://www.everionconsulting.com/tr/blog/25"}',10,1),
('articles','salesforce-crm','{"title_tr":"Salesforce ve CRM","title_en":"Salesforce and CRM","summary_tr":"CRM yaklaşımını ve Salesforce’un müşteri süreçlerini tek platformda nasıl birleştirdiğini açıklıyorum.","summary_en":"An introduction to CRM thinking and how Salesforce brings customer processes together on one platform.","publication":"Everion Consulting","language":"tr","topics":["Salesforce","CRM"],"url":"https://www.everionconsulting.com/tr/blog/9"}',11,1),
('articles','django-introduction','{"title_tr":"Django’ya Giriş","title_en":"Introduction to Django","summary_tr":"Django’nun temel yapısını, geliştirme yaklaşımını ve hızlı ürün geliştirmedeki avantajlarını anlatıyorum.","summary_en":"An introduction to Django’s core structure, development approach and advantages for rapid product development.","publication":"Everion Consulting","language":"tr","topics":["Django","Python"],"url":"https://www.everionconsulting.com/tr/blog/3"}',12,1);

INSERT INTO site_settings(key,value) VALUES
('seo_title_tr','Gökçe Güler | Full-Stack Yazılım Mühendisi'),
('seo_title_en','Gökçe Güler | Full-Stack Software Engineer'),
('seo_description_tr','Gökçe Güler’in full-stack yazılım mühendisliği deneyimi, ürün katkıları, kişisel projeleri, Salesforce sertifikaları ve teknik yazıları.'),
('seo_description_en','Gökçe Güler’s full-stack software engineering experience, product contributions, personal projects, Salesforce credentials and technical writing.'),
('about_lead_tr','İş problemlerini yalnızca kod yazarak değil; süreç, veri modeli, güvenlik ve kullanıcı deneyimiyle birlikte ele alan bir yazılım mühendisiyim.'),
('about_lead_en','I am a software engineer who approaches business problems through process, data modeling, security and user experience—not code alone.'),
('about_body_tr','Backend, web ve mobil ürünler geliştirirken mimariden yayına kadar sorumluluk alıyorum. Salesforce; deklaratif ve programatik çözümler, platform sınırları, yetkilendirme ve otomasyon arasındaki ilişkiye bakışımı genişletti. Certified Administrator ve Agentforce Specialist sertifikalarımın ardından Platform Developer I sınavına hazırlanıyorum.'),
('about_body_en','I work across backend, web and mobile products, taking responsibility from architecture through release. Salesforce broadened how I think about declarative and programmatic solutions, platform limits, permissions and automation. After earning the Certified Administrator and Agentforce Specialist credentials, I am preparing for Platform Developer I.')
ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP;

PRAGMA foreign_keys=ON;
