import {apiBase} from "@/lib/api";

export type Locale="tr"|"en";
export type Section="about"|"experience"|"work"|"contact";

export const copy={
  tr:{nav:["Hakkımda","Deneyim","Projeler","İletişim"],navDesc:["Yaklaşımım, yetkinliklerim ve özgeçmişim","Roller, sorumluluklar ve üretim deneyimi","Ürünler, sistemler ve teknik detaylar","Bir fikir veya iş birliği için"],about:"Teknik yaklaşımım",work:"Geliştirdiğim seçkin sistemler",workNote:"Karmaşık iş akışlarını sade, güvenilir ürünlere dönüştürdüğüm bazı çalışmalar.",otherWorks:"Diğer Çalışmalar",otherWorksNote:"Daha küçük ölçekte geliştirdiğim araçlar, deneyler ve teknik üretimler.",experience:"Mühendislik deneyimlerim",experienceNote:"Ürün geliştirme, teknik koordinasyon ve production sorumluluğunun zaman içindeki gelişimi.",education:"Eğitim",skills:"Teknik yetkinlikler",certs:"Sertifikalar",library:"Özgeçmişimi incele",libraryNote:"Deneyimimin ayrıntılı dökümüne Türkçe veya İngilizce ulaşabilirsin.",contact:"Gelin birlikte tasarlayalım",open:"Aç / indir",close:"Kapat",back:"Geri",present:"Şu an",current:"Devam ediyor",apiOffline:"Portfolyo API’sine ulaşılamıyor.",apiHelp:"Go API’yi başlatınca içerikler burada görünecek.",detail:"Detayları gör",role:"Rol",problem:"Problem",overview:"Katkım",highlights:"Öne çıkanlar",outcome:"Sonuç",stack:"Teknolojiler",visit:"Ürün sitesini ziyaret et",source:"GitHub’da incele",openSource:"Açık kaynak"},
  en:{nav:["About","Experience","Projects","Contact"],navDesc:["Approach, capabilities and résumé","Roles, responsibilities and production work","Products, systems and technical details","For an idea or collaboration"],about:"My technical approach",work:"Selected systems I've built",workNote:"A few systems where I turned complicated operations into calm, dependable products.",otherWorks:"Other Work",otherWorksNote:"Smaller tools, experiments and technical work I've built along the way.",experience:"Engineering experience",experienceNote:"A progression through product delivery, technical coordination and production ownership.",education:"Education",skills:"Technical capabilities",certs:"Certifications",library:"View my résumé",libraryNote:"Explore a detailed account of my experience in Turkish or English.",contact:"Let's build something together",open:"Open / download",close:"Close",back:"Back",present:"Present",current:"In progress",apiOffline:"The portfolio API is offline.",apiHelp:"Start the Go API and the content will appear here.",detail:"View details",role:"Role",problem:"Problem",overview:"My contribution",highlights:"Highlights",outcome:"Outcome",stack:"Tech stack",visit:"Visit product site",source:"View on GitHub",openSource:"Open source"}
};

export type Copy=(typeof copy)[Locale];

export function localized(item:Record<string,unknown>,key:string,locale:Locale){return String(item[`${key}_${locale}`]??item[key]??"")}
export function localizedList(item:Record<string,unknown>,key:string,locale:Locale){const value=item[`${key}_${locale}`]??item[key];if(Array.isArray(value))return value.map(String).filter(Boolean);if(typeof value==="string")return value.split(/\r?\n/).map(part=>part.trim()).filter(Boolean);return []}
export function assetUrl(value?:string){if(!value)return "";if(value.startsWith("/uploads/"))return `${apiBase}${value}`;return value}
