"use client";
import {useEffect,useRef} from "react";
import {Item} from "./schema";

export default function DeleteDialog({target,schemaTitle,deleting,onCancel,onConfirm}:{target:Item;schemaTitle:string;deleting:boolean;onCancel:()=>void;onConfirm:()=>void}){
  const dialogRef=useRef<HTMLDivElement>(null);const cancelRef=useRef<HTMLButtonElement>(null);const previousFocus=useRef<HTMLElement|null>(null);const cancelAction=useRef(onCancel);const deletingState=useRef(deleting);cancelAction.current=onCancel;deletingState.current=deleting;
  useEffect(()=>{previousFocus.current=document.activeElement as HTMLElement;cancelRef.current?.focus();const onKey=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!deletingState.current){event.preventDefault();cancelAction.current();return}if(event.key!=="Tab"||!dialogRef.current)return;const buttons=[...dialogRef.current.querySelectorAll<HTMLButtonElement>("button:not([disabled])")];if(!buttons.length)return;const first=buttons[0],last=buttons[buttons.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};document.addEventListener("keydown",onKey);return()=>{document.removeEventListener("keydown",onKey);previousFocus.current?.focus()}},[]);
  return <div className="admin-dialog-backdrop" role="presentation" onMouseDown={()=>{if(!deleting)onCancel()}}><div ref={dialogRef} className="admin-dialog" role="alertdialog" aria-modal="true" aria-labelledby="admin-delete-title" aria-describedby="admin-delete-description" aria-busy={deleting} onMouseDown={event=>event.stopPropagation()}><span className="admin-dialog-mark" aria-hidden="true">!</span><h2 id="admin-delete-title">Kaydı sil?</h2><p id="admin-delete-description"><strong>{String(target.data[schemaTitle]||target.slug)}</strong> kalıcı olarak silinecek.</p><div className="editor-actions"><button ref={cancelRef} type="button" className="secondary" disabled={deleting} onClick={onCancel}>Vazgeç</button><button type="button" className="danger" disabled={deleting} onClick={onConfirm}>{deleting?"Siliniyor…":"Sil"}</button></div></div></div>;
}
